model:
  algorithm: SAC
  learning_rate: 0.0003
  verbose: 1
  net_arch:
    pi:
    - 256
    - 256
    - 256
    qf:
    - 256
    - 256
    - 256
  use_her: true
  her_n_sampled_goal: 4
  her_goal_selection_strategy: final
session:
  total_timesteps: 250000
  callbacks:
  - csv_logger
  - checkpoint
  - eval
  - success_rate
  pretrained_model_path: experiments/PathPlanningGoalEnv-v0/SAC/models/20260409_131016/final_model.zip
  train_groups: null
  eval_groups: null
  eval_episodes: 10
  do_train: true
  do_evaluate: true
  eval_freq: 25000
  track_training_evals: false
env:
  env_kwargs:
    action_mode: hdg
    rta_sampler_path: path_planning/rta/data/models/runway_sampler_deterministic_extra_trees_100.pkl
    runways: null
  env_name: PathPlanningGoalEnv-v0
  success_key: is_success
  group_key: current_runway
